name: Draft release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags: 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 6
      id: setup_jdk_6
      uses: actions/setup-java@v1
      with:
        java-version: 6
    - name: Set up JDK 17
      id: setup_jdk_17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Install advancecomp
      run: sudo apt-get install advancecomp
    - name: Install strip-nondeterminism
      run: sudo apt-get install strip-nondeterminism
    - name: Build with Gradle
      env:
        GITHUB_ACTIONS_JDK_6: ${{ steps.setup_jdk_6.outputs.path }}
        GITHUB_ACTIONS_JDK_17: ${{ steps.setup_jdk_17.outputs.path }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_RELEASE: ${{ github.event.release.prerelease == false }}
      uses: gradle/gradle-build-action@v1
      with:
        gradle-version: wrapper
        distributions-cache-enabled: false
        dependencies-cache-enabled: false
        configuration-cache-enabled: false
        arguments: build publish
    - name: Run strip-nondeterminism on built .jar files
      run: strip-nondeterminism mc-texture-gen-app/build/libs/*.jar
    - name: Run advzip on built .jar files
      run: advzip --shrink-insane --iter 99999 -k -p -z mc-texture-gen-app/build/libs/*.jar
    - name: Draft release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Draft release ${{ github.ref }}
        body: Replace this text with the description of this release!
        draft: true
        prerelease: false
    - name: Upload draft release assets
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: mc-texture-gen-app/build/libs/*.jar
