name: Build on push or pull request (main)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up JDK 6 & 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: |
          6
          17
    - name: Install advancecomp
      run: sudo apt-get install advancecomp
    - name: Install strip-nondeterminism
      run: sudo apt-get install strip-nondeterminism
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Build with Gradle
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
        arguments: build publish --scan --stacktrace --warning-mode all
    - name: Run strip-nondeterminism on built .jar files
      run: strip-nondeterminism mc-texture-gen-app/build/libs/*.jar
    - name: Run advzip on built .jar files
      run: advzip --shrink-insane --iter 999 -k -p -z mc-texture-gen-app/build/libs/*.jar
    - name: Run ECT on built .jar files
      run: for file in ./build/libs/*.jar; do ./ci-tools/ect-ubuntu-x86-64 --disable-png --disable-jpg -strip -zip $file; done
    - name: Run ECT (-9) on built .jar files
      run: for file in ./build/libs/*.jar; do ./ci-tools/ect-ubuntu-x86-64 -9 --disable-png --disable-jpg -strip -zip $file; done
    - name: Run ECT (-99) on built .jar files
      run: for file in ./build/libs/*.jar; do ./ci-tools/ect-ubuntu-x86-64 -99 --disable-png --disable-jpg -strip -zip $file; done
    - name: Run ECT (-30060) on built .jar files
      run: for file in ./build/libs/*.jar; do ./ci-tools/ect-ubuntu-x86-64 -30060 --disable-png --disable-jpg -strip -zip $file; done
    - name: Run ECT (-90032) on built .jar files
      run: for file in ./build/libs/*.jar; do ./ci-tools/ect-ubuntu-x86-64 -90032 --disable-png --disable-jpg -strip -zip $file; done
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: mc-texture-gen-app/build/libs
